### ISSUE TITLE
Need some help?

### ISSUE THREAD

**Issue by codewisdom** [markjsc/AutoMockHelper#7]
HI Mark,

I'm a .NET dev looking to make some open source contributions.  I really like this project!  Any chance you'd be open to some help updating and/or extending it?  I have some rough ideas already, but I'd rather take direction from you to if you have some ideas.  We can connect here or elsewhere.  Look forward to your response.

Best regards,
Sam

**Comment by markjsc** [comment]
Hi @codewisdom (Sam),
Thanks so much for your interest! As you can see from the commit history, this project is pretty much dormant. I originally built it while I was developing and maintaining several systems that needed this type of solution. But I've shifted my focus into different types of development in the past 2-3 years and I don't currently have any systems that use this.

Nevertheless, I would be take any suggested improvements and I would be very thankful for any assistance you could provide.

Did you have any specific changes in mind? Other than staying in sync with Moq and AutoMock, I don't know of anything pressing.

Thanks,
Mark

**Comment by codewisdom** [comment]
Nothing specific other than getting in sync with current Moq and AutoMock is my first thought.  If you are concerned about potentially breaking existing users, I could fork off of this project.  I don't know off the top of my head of there would be breaking changes - I suspect not.  Of course, I would create a private fork for any changes you might accept into this repo.

**Comment by codewisdom** [comment]
Hi Mark,

Forgive me, I forgot one thing I really would like to add.  Assuming it's possible, I'd like to add a `VerifyFor<TMock>() `method.  I rarely if ever use VerifyAll() myself.  I like explicit verify calls.

Regards,
Sam

**Comment by codewisdom** [comment]
Hi Mark, 

I played around for a few minutes.  This is not complete and a rough cut, but this works just fine for me:

```
public void VerifyFor<TDependency>(Expression<Action<TDependency>> expression, Times times)
where TDependency : class
{
  this.AutoMocker.GetMock<TDependency>()
      .Verify(expression, times);
}

public void VerifyFor<TDependency>(Expression<Action<TDependency>> expression, Func<Times> funcTimes)
where TDependency : class
{
  this.AutoMocker.GetMock<TDependency>()
    .Verify(expression, funcTimes);
}
```

What do you think?

Regards,
Sam

**Comment by markjsc** [comment]
Thanks for your contribution and I think that makes sense. I'll shake off the cobwebs and take a closer look sometime later this weekend.
Stay tuned - and much appreciated!

-mark

**Comment by markjsc** [comment]
Hi Sam - I've submitted PR #8 
Please take a look to see what you think. I used the name `Verify()` instead of `VerifyFor`, just thinking it's a bit more clear since we have a `VerifyAll()` and a `VerifyCallsFor()`.
I also made a few more "keep with the times" updates (updated dependencies, changed target to .NET Standard 2.0, etc).

Please review and let me know if you have any additional feedback. (Feel free to push to the same branch used in the PR, if permissions allow.)

**Comment by codewisdom** [comment]
Hi Mark!

The PR looks great to me. I pulled it down to look around and run the tests locally.  I have one other extension to this I'd like to try on you, but I'd prefer to write that up myself in a separate PR if you don't mind.  I think that would be cleaner.  I don't mind the Verify name at all - you are the owner you get to make those calls.

I'll fork the entire repo and send you a PR from there.  I plan on doing that early next week sometime, if not sooner!  I doubt I can push to this repo directly anyways.

Thanks again for making these changes.  This will help me sell this internally where I work! 

Regards,
Sam

**Comment by markjsc** [comment]
Hi Sam - I've updated Readme.md with some details of the recent changes and PR'd it into `master` (#9) . I also updated the encrypted NuGet API Key used by AppVeyor to automatically publish the assets from the `release` branch to NuGet. It took me several PRs into master and then release to get everything working correctly (it's been about 3 years since I set this up and I had to dig a bit to recall how to update and encrypt the API keys).

You're certainly welcomed to Fork as you like, but I would be happy to continue applying any of your enhancement requests directly to this repo.

Thanks again for the kick-start to keep this project moving forward!

**Comment by markjsc** [comment]
Hi Sam - I'm going to close this issue based on the changes we worked on last weekend. I'm not sure of the way the "cool kids" are communicating around GitHub work these days, but feel free to direct message me (?) or create another issue as you become aware of bugs or new features.
Thanks again for your help!
-mark
